--liquibase formatted sql
--changeset Mirko:create-tables spitStatement:true andDelimiter:;


INSERT INTO users VALUES (
1,1,'$2a$10$Whcr6HD8FI6/TsaH0nqyMuF8nEYkw987FBkcraT3wLBPSJlnE5/te','ROLE_USER','user1'
);
INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (

'MODNA,FORMULA,REVIJA,SLETETI,PISTA',
'PTICA,ŠATOR,FUDBAL,KOŠARKA,KRILO',
'MUZIČKA GRUPA,CAR KONSTANTIN,NIKOLA TESLA,VOJNI,AERODROM',
'KIKI LESENDRIĆ,NAOČARE,MASKA,ODELO,PILOT',
'AVION'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'DONJI,MAŠINA,DASKA,ČISTI,VEŠ',
'ŠAH,MINA,KOSOVO,OPASNO,POLJE',
'RUŽA,LALA,HRIZANTEMA,MIRIS,CVET',
'BELA,NAVIJAČKA,BRATELE,BEZ RUKAVA,MAJICA',
'PAMUK'
);
INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'HIGIJENA,LEPOTA,LESKOVAC,DOKTOR,ZDRAVLJE',
'BOKVICA,ZA MRŠAVLJENJE,ZA ISKAŠLJAVANJE,OD JAVORA,SIRUP',
'ALCHAJMEROVA,LAJMSKA,PRENOSIVA,NEIZLEČIVA,BOLEST',
'CRNA,MUZIČKA,ŠIBICA,CIGARETA,KUTIJA',
'LEK'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'CRNA,BELA,ŠVAJCARSKA,MILKA,ČOKOLADA',
'SIPINA,KLJUČNA,BUTNA,KALCIJUM,KOST',
'KRIVA,PRŠLJENOVI,STUB,MOŽDINA,KIČMA',
'GREJANJE,ELEKTRIČNI,GREJNO TELO,GASNI,RADIJATOR',
'REBRO'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'OPIJUM,ŠTRUDLA,MAKEDONIJA,U ŽITU,MAK',
'BABIN,KRUNA,ZLATNI,PLOMBA,ZUB',
'PUT,TKANINA,BUBA,BOMBONA,SVILA',
'ŠPRIC,ŠIVENJE,UŠI,U PLASTU SENA,IGLA',
'KONAC'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'U TETRAPAKU,CEĐENI,PRIRODNI,NA CEVČICU,SOK',
'ADAM I EVA,ZABRANJENO VOĆE,ZLATNI DELIŠES,PITA,JABUKA',
'KORA,PAKLENA,ĐUS,CEĐENA,POMORANDŽA',
'GRČKA,SRPSKA,ŠOPSKA,MEŠANA,SALATA',
'VOĆE'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'CVEĆE,UKRASNA,NA TERASI,BAŠTENSKA,SAKSIJA',
'MAČKA,SIR,DŽERI,BRZI GONZALES,MIŠ',
'KAFA,NOĆ,BOJA,BELA,CRNA',
'ŠVAJCARSKI,RUPICE,BUĐAVI,MLEČNI,SIR',
'RUPA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'CRNO,CRVENO,NEUTRALNO,HORIZONTE,BELO',
'GRLO,MESO,ŠLJIVA,VOĆE,SUVO',
'IN ... VERITAS,CRVENO,CRNO,ALKOHOLNO PIĆE,VINO',
'SVINJSKA,RIBLJA,ZA PRŽENJE,MRLJA,MAST',
'GROŽĐE'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'OBALA,TOK,KORITO,DUNAV,REKA',
'DRVO,ZUBI,GLODAR,PLIVAČ,DABAR',
'TERMO,ĐERDAP,NUKLEARNA,HIDRO,ELEKTRANA',
'SKADAR,VODA,PALIĆ,TITIKAKA,JEZERO',
'BRANA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'PRAVDA,KIJANJE,LAŽ,GOLA,ISTINA',
'PINK,DEVOJČICE,POZE,BOJA,ROZE',
'BRAŠNO,GROŽĐE,MESO,CRNO,BELO',
'ETANOL,POROK,VRENJE,METIL,ALKOHOL',
'VINO'
);


INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'DESNA RUKA,TROJNO,IZUZETAK,ZLATNO,PRAVILO',
'ČOVEK,PRAZNIK,VREME,NALOG,RAD',
'ARTUR MILER,PLAVUŠA,PLEJBOJ,NEKI TO VOLE VRUĆE,MERLIN MONRO',
'METROPOLITEN,SCENA,MUZIKA,BUFFA,OPERA',
'NORMA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'MOST,DELTA,TISA,SAVA,REKA',
'MOZAK,DRŽAVA,GROM,SRCE,UDAR',
'ZASTAVICA,PALICA,RUPA,LOPTICA,GOLF',
'SREĆA,UŽICE,FOLKLOR,BRANKO,KOLO',
'STRUJA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'UDOVICA,NOĆ,GORA,MAČKA,CRNA',
'BORA DUGIĆ,PAN,DUVANJE,MUZIKA,FRULA',
'SIR,GLODANJE,RAČUNAR,MAČKA,MIŠ',
'TRI,KISEONIK,OMOTAČ,VISOKI NAPON,OZON',
'RUPA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'VREME,DESNI,MLEKO,ZLATO,ZUB',
'CIPELE,PERTLA,KOŽA,ČIZME,OBUĆA',
'TORINO,PIZA,VESPAZIJAN,FIAT,ITALIJA',
'PALAČINKE,BRAŠNO,LISNATO,PIZZA,TESTO',
'PASTA'
);


INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'LIVADA,LATICE,TUČAK,MED,CVET',
'TELO,ČOKOLADA,PRAH,JAGODA,MLEKO',
'TORTILJA,SITI,SOMBRERO,ČILI,MEKSIKO',
'PRASE,JEŽ,PČELA,RUŽA,BODLJA',
'KAKTUS'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES ('TRUDNICA,GRČ,VARENJE,KISELINA,STOMAK',
'SAT,ĆELIJA,KINA,ŽIVI,ZID',
'KADA,OGLEDALO,TURSKA,TUŠ,KUPATILO',
'PEDALA,ZAUSTAVLJANJE,RUĆNA,ULJE,KOČNICA',
'PLOČICE'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'AMOROVA STRELA,KOMORA,LJUBAV,MIŠIĆ,SRCE',
'STAKLO,SLATKO,AJVAR,POKLOPAC,TEGLA',
'CVEĆE,STOKA,TRAVA,POLJANA,LIVADA',
'POŽAR,STABLA,ČETINARI,ROBIN HUD,ŠUMA',
'MED'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'RUSKA,KUPUS,VOĆE,CEZAR,SALATA',
'BRAVA,MATICA,EMISIJA,PRIVEZAK,KLJUČ',
'STRAST,OBRAZ,LJUBAV,VATRA,POLJUBAC',
'KUGLA,KREVET,BOLNICA,KAUČ,LEŽAJ',
'FRANCUSKI'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'DVORANA,DUBOK,RAZLIKA,GENERACIJA,JAZ',
'SOBA,JAPANKE,OBUĆA,LETO,PAPUČE',
'KAMEN,REČNO DNO,PESAK,BETON,ŠLJUNAK',
'ZAŠTITA,FRIKOM,SUNCE,PLATNO,SUNCOBRAN',
'PLAŽA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'GALAPAGOS,ZEC,MORE,SUPA,KORNJAČA',
'PERISKOP,ATOM,ŽIL VERN,KURSK,PODMORNICA',
'GUSENICA,T-84,BRDO,CEV,TENK',
'SREDNJI VEK,KOJA,HRABRI,OKRUGLI STO,VITEZ',
'OKLOP'
);

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'RODBINSKE VEZE',
'1:SNAJA, 2:JETRVA, 3:ZAOVA, 4:SVASTIKA, 5:ŠURNJAJA, 6:SVEKRVA, 7:TAŠTA, 8:STRINA',
'3:MUŽEVLJEVA SESTRA, 5:ŽENA ŽENINOG BRATA, 1:BRATOVA ŽENA, 8:ŽENA OČEVOG BRATA, 2:ŽENA MUŽEVLJEVOG BRATA, 4:ŽENINA SESTRA, 7:ŽENINA MAJKA, 6:MUŽEVLJEVA MAJKA'
);

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'SPOJITE GRADOVE SA SVOJIM NEKADAŠNJIM NAZIVIMA',
'1:BEOGRAD, 2:SREMSKA MITROVICA, 3:DŽAKARTA, 4:KNJAŽEVAC, 5:JAGODINA, 6:NJUJORK, 7: BRATISLAVA, 8:PODGORICA',
'5:SVETOZAREVO, 2:SIRMIJUM, 3:BATAVIJA, 8:TITOGRAD, 1:SINGIDUNUM, 4:GURGUSOVAC, 7:PRESBURG, 6:NOVI AMSTERDAM'
);

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'SPOJITE LIKOVE IZ CRTANIH FILMOVA SA ŽIVOTINJOM KOJU PREDSTAVLJAJU',
'1:SILVESTER, 2:MLATA, 3:BAJA, 4:DŽERI, 5:MANFRED, 6:MARTI, 7:GLORIJA, 8:MAJOR',
 '2:PAS, 5:MAMUT, 7:NILSKI KONJ, 3:PATAK, 6:ZEBRA, 1:MAČAK, 4:MIŠ, 8:PINGVIN'
 );

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'POVEŽITE SPORTSKE RIVALE',
'1:OLIMPIJAKOS, 2:ČELZI, 3:DINAMO, 4:SELTIK, 5:FEHERBAHČE, 6:LACIO, 7:BENFIKA, 8:AJAKS',
'4:RENDŽERS, 2:ARSENAL, 5:GALATASARAJ, 7:SPORTING, 3:HAJDUK, 6:ROMA, 8:FEJNORD, 1:PANATANAIKOS'
);

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'POVEŽITE GODINE I POBEDNIKE EUROSONGA',
'1:2008., 2:2006., 3:2009., 4:2005., 5:2007., 6:2010., 7:2004., 8:2003.',
 '6:NEMAČKA-LENA, 2:FINSKA-LORDI, 5:SRBIJA-M.ŠERIFOVIĆ, 3:NORVEŠKA-A.RIBAK, 1:RUSIJA-DIMA BILAN, 8:TURSKA-S.ERENER, 4:GRČKA-H.PAPARIZOU, 7:UKRAJINA-RUSLANA'
 );

INSERT INTO pairs_model (headline, column1, column2) VALUES (
'SPOJITE PRONALAZAČE SA NJIHOVIM IZUMIMA',
 '1:INDUKCIONA MAŠINA, 2:PENICILIN, 3:ELEKTRONSKA POŠTA, 4: NUKLEARNI REAKTOR, 5:GROMOBRAN, 6:ŽIROSKOP, 7:TRAKTOR, 8:RADIO TALASI',
 '4:ENRIKO FERMI, 6:LEON FUKO, 8:HAJNRIH HERC, 1:NIKOLA TESLA, 3:REJ TOMPLINSON, 7: BENDŽAMIN HOLT, 2: ALEKSANDAR FLEMING, 5:BENDŽAMIN FRENKLIN'
 );

 INSERT INTO pairs_model (headline, column1, column2) VALUES (
 'POVEŽITE PISCE I NJIHOVA DELA',
 '1:IVO ANDRIĆ, 2:VIKTOR IGO, 3:LAJOS ZILAHY, 4:MARK TVEN, 5:MEŠA SELIMOVIĆ, 6:MILOŠ CRNJANSKI, 7:ALEKSA ŠANTIĆ, 8:MOMO KAPOR',
 '3:KAD DUŠA ZAMRE, 7:HASANAGINICA, 2:JADNICI, 5:TVRĐAVA, 8:HRONIKA IZGUBLJENOG GRADA, 6:SEOBE, 1:TRAVNIČKA HRONIKA, 4:AVANTURE HAKLBERI FINA'
 );

 INSERT INTO pairs_model (headline, column1, column2) VALUES (
 'SPOJITE POZNATA PIĆA SA DRŽAVAMA POREKLA',
 '1:GINIS, 2:APSENT, 3:LOZOVAČA, 4:BURGUNDAC, 5:TEKILA, 6:RAKI, 7:METAKSA, 8:KAPIROSKA',
 '6:TURSKA, 4:FRANCUSKA, 2:ČEŠKA, 8:BRAZIL, 1:IRSKA, 7:GRČKA, 5:MEKSIKO, 3:CRNA GORA'
 );

 INSERT INTO pairs_model (headline, column1, column2) VALUES (
 'SPOJITE SRPSKE VOJSKOVOĐE SA MESTOM ROĐENJA',
 '1:HAJDUK VELJKO, 2:STANOJE GLAVAŠ, 3:VUK ISAKOVIĆ, 4:KARAĐORĐE PETROVIĆ, 5:STOJAN ČUPIĆ, 6:VASA ČARAPIĆ, 7:LAZAR HREBELJANOVIĆ, 8:PETAR DOBRNJAC',
 '1:LENOVAC, 6:BELI POTOK, 3:SREDSKA, 8:DOBRINJE, 5:PIVA, 2:GLIBOVAC, 7:PRILEPAC, 4:VIŠEVAC'
 );

INSERT INTO pairs_model (headline, column1, column2) VALUES (
'SPOJITE SKRAĆENICE SA POJMOVIMA KOJE OZNAČAVAJU',
'1:DC, 2:GPS, 3:HTML, 4:ISO, 5:JPEG, 6:PHP, 7:DIN, 8:NIN',
'3:OPISNI JEZIK WEB STRANICA, 7:FABRIKA DUVANA, 8:INFORMATIVNE NOVINE, 5:FORMAT ZA SLIKE, 2:NAVIGACIONI SISTEM, 4:STANDARD, 1:JEDNOSMERNA STRUJA, 6:SKRIPTNI JEZIK'
);

INSERT INTO pairs_model (headline, column1, column2) VALUES (
'SPOJITE GRAĐEVINE SA ZEMLJAMA U KOJIMA SE NALAZE',
'1:KINKAKU-ĐI, 2:BELVEDERE, 3:DESPIĆA KUĆA, 4:ZEPION, 5:PENTOMINIUM, 6:BIG BEN, 7:KREMLJ, 8:KRISTALNA PALATA',
'5:DUBAI, 8:SLOVENIJA, 3:BIH, 6:ENGLESKA, 1:JAPAN, 4:GRČKA, 7:RUSIJA, 2:AUSTRIJA'
);

INSERT INTO pairs_model (headline, column1, column2) VALUES (
'SPOJITE NOVČANICE SA OSOBAMA ČIJI SE LIKOVI NALAZE NA NJIMA',
'1:10 RSD, 2:1 USD, 3:5000 USD, 4:5 USD, 5:10 GBP, 6:50 RSD, 7:20 USD, 8:200 RSD',
'6:STEVAN MOKRANJAC, 1:VUK KARADŽIĆ, 4:ABRAHAM LINKOLN, 7:ENDRJU DŽEKSON, 2:DŽORDŽ VAŠINGTON, 5:ČARLS DARVIN, 8:NADEŽDA PETROVIĆ, 3:SLOBODAN JOVANOVIĆ'
);

INSERT INTO pairs_model (headline, column1, column2) VALUES (
'SPOJITE OZNAKE SA VRSTOM NAORUŽANJA KOJEM PRIPADAJU',
'1:KA-52, 2:S-400, 3:T-90, 4:RQ-7, 5:M-249, 6:SU-35, 7:AN-124, 8:E-3',
'8:AWACS, 3:TENK, 6:BORBENI AVION, 1:BORBENI HELIKOPTER, 4:BESPILOTNA LETELICA, 7:BORBENI AVION, 2:PVO SISTEM, 5:PUŠKOMITRALJEZ'
);

INSERT INTO pairs_model (headline, column1, column2) VALUES (
'SPOJITE BROJEVE SA NJIHOVIM NAJMANJIM ZAJEDNIČKIM SADRŽAOCEM',
'1:2 I 7, 2:3 I 8, 3:9 I 6, 4:2 I 4, 5:4 I 7, 6:2 I 11, 7:15 I 6, 8:18 I 4',
'2:24, 5:28, 8:36, 3:18, 6:22, 1:14, 4:4, 7:30'
);

INSERT INTO pairs_model (headline, column1, column2) VALUES (
'SPOJITE POZIVNE BROJEVE SA DRŽAVAMA',
'1:34, 2:7, 3:44, 4:32, 5:46, 6:359, 7:39, 8:420',
'5:ŠVEDSKA, 2:RUSIJA, 7:ITALIJA, 4:BELGIJA, 1:ŠPANIJA, 6BUGARSKA, 3:ENGLESKA, 8: ČEŠKA'
);

INSERT INTO pairs_model (headline, column1, column2) VALUES (
'SPOJITE DRŽAVE SA VREMENSKIM ZONAMA KOJIMA PRIPADAJU',
'1:GMT MINUS 4, 2:GMT PLUS 12, 3:GMT PLUS 10, 4:GMT PLUS 9, 5:GMT PLUS 11, 6:GMT MINUS 3, 7:GMT PLUS 8, 8:GMT MINUS 5',
'7:AUSTRALIJA, 4:JAPAN, 1:PORTORIJKO, 6:ARGENTINA, 3:PAPUA NOVA GVINEJA, 8:JAMAJKA, 5:NOVA KALEDONIJA, 2:NOVI ZELAND'
);

INSERT INTO pairs_model (headline, column1, column2) VALUES (
'SPOJITE MODELE AUTOMOBILA SA GODINOM KADA SU SE POJAVILI NA TRŽIŠTU',
'1:FIJAT 500L, 2:JUGO FLORIDA, 3:ZASTAVA 101, 4:ZASTAVA 750 (FIĆA), 5:GOLF 2, 6:MERCEDES BENC W136, 7:ŠKODA FABIA, 8:VARTBURG 353',
'1:2012, 4:1955, 7:1999, 2:1988, 5:1983, 8:1966, 3:1971, 6:1936'
);