--liquibase formatted sql
--changeset Mirko:create-tables spitStatement:true andDelimiter:;


INSERT INTO users VALUES (
1,1,"$2a$10$Whcr6HD8FI6/TsaH0nqyMuF8nEYkw987FBkcraT3wLBPSJlnE5/te","ROLE_USER","user1"
)
;
INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (

'MODNA,FORMULA,REVIJA,SLETETI,PISTA',
'PTICA,ŠATOR,FUDBAL,KOŠARKA,KRILO',
'MUZIČKA GRUPA,CAR KONSTANTIN,NIKOLA TESLA,VOJNI,AERODROM',
'KIKI LESENDRIĆ,NAOČARE,MASKA,ODELO,PILOT',
'AVION'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'DONJI,MAŠINA,DASKA,ČISTI,VEŠ',
'ŠAH,MINA,KOSOVO,OPASNO,POLJE',
'RUŽA,LALA,HRIZANTEMA,MIRIS,CVET',
'BELA,NAVIJAČKA,BRATELE,BEZ RUKAVA,MAJICA',
'PAMUK'
);
INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'HIGIJENA,LEPOTA,LESKOVAC,DOKTOR,ZDRAVLJE',
'BOKVICA,ZA MRŠAVLJENJE,ZA ISKAŠLJAVANJE,OD JAVORA,SIRUP',
'ALCHAJMEROVA,LAJMSKA,PRENOSIVA,NEIZLEČIVA,BOLEST',
'CRNA,MUZIČKA,ŠIBICA,CIGARETA,KUTIJA',
'LEK'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'CRNA,BELA,ŠVAJCARSKA,MILKA,ČOKOLADA',
'SIPINA,KLJUČNA,BUTNA,KALCIJUM,KOST',
'KRIVA,PRŠLJENOVI,STUB,MOŽDINA,KIČMA',
'GREJANJE,ELEKTRIČNI,GREJNO TELO,GASNI,RADIJATOR',
'REBRO'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'OPIJUM,ŠTRUDLA,MAKEDONIJA,U ŽITU,MAK',
'BABIN,KRUNA,ZLATNI,PLOMBA,ZUB',
'PUT,TKANINA,BUBA,BOMBONA,SVILA',
'ŠPRIC,ŠIVENJE,UŠI,U PLASTU SENA,IGLA',
'KONAC'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'U TETRAPAKU,CEĐENI,PRIRODNI,NA CEVČICU,SOK',
'ADAM I EVA,ZABRANJENO VOĆE,ZLATNI DELIŠES,PITA,JABUKA',
'KORA,PAKLENA,ĐUS,CEĐENA,POMORANDŽA',
'GRČKA,SRPSKA,ŠOPSKA,MEŠANA,SALATA',
'VOĆE'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'CVEĆE,UKRASNA,NA TERASI,BAŠTENSKA,SAKSIJA',
'MAČKA,SIR,DŽERI,BRZI GONZALES,MIŠ',
'KAFA,NOĆ,BOJA,BELA,CRNA',
'ŠVAJCARSKI,RUPICE,BUĐAVI,MLEČNI,SIR',
'RUPA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'CRNO,CRVENO,NEUTRALNO,HORIZONTE,BELO',
'GRLO,MESO,ŠLJIVA,VOĆE,SUVO',
'IN ... VERITAS,CRVENO,CRNO,ALKOHOLNO PIĆE,VINO',
'SVINJSKA,RIBLJA,ZA PRŽENJE,MRLJA,MAST',
'GROŽĐE'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'OBALA,TOK,KORITO,DUNAV,REKA',
'DRVO,ZUBI,GLODAR,PLIVAČ,DABAR',
'TERMO,ĐERDAP,NUKLEARNA,HIDRO,ELEKTRANA',
'SKADAR,VODA,PALIĆ,TITIKAKA,JEZERO',
'BRANA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'PRAVDA,KIJANJE,LAŽ,GOLA,ISTINA',
'PINK,DEVOJČICE,POZE,BOJA,ROZE',
'BRAŠNO,GROŽĐE,MESO,CRNO,BELO',
'ETANOL,POROK,VRENJE,METIL,ALKOHOL',
'VINO'
);


INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'DESNA RUKA,TROJNO,IZUZETAK,ZLATNO,PRAVILO',
'ČOVEK,PRAZNIK,VREME,NALOG,RAD',
'ARTUR MILER,PLAVUŠA,PLEJBOJ,NEKI TO VOLE VRUĆE,MERLIN MONRO',
'METROPOLITEN,SCENA,MUZIKA,BUFFA,OPERA',
'NORMA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'MOST,DELTA,TISA,SAVA,REKA',
'MOZAK,DRŽAVA,GROM,SRCE,UDAR',
'ZASTAVICA,PALICA,RUPA,LOPTICA,GOLF',
'SREĆA,UŽICE,FOLKLOR,BRANKO,KOLO',
'STRUJA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'UDOVICA,NOĆ,GORA,MAČKA,CRNA',
'BORA DUGIĆ,PAN,DUVANJE,MUZIKA,FRULA',
'SIR,GLODANJE,RAČUNAR,MAČKA,MIŠ',
'TRI,KISEONIK,OMOTAČ,VISOKI NAPON,OZON',
'RUPA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'VREME,DESNI,MLEKO,ZLATO,ZUB',
'CIPELE,PERTLA,KOŽA,ČIZME,OBUĆA',
'TORINO,PIZA,VESPAZIJAN,FIAT,ITALIJA',
'PALAČINKE,BRAŠNO,LISNATO,PIZZA,TESTO',
'PASTA'
);


INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'LIVADA,LATICE,TUČAK,MED,CVET',
'TELO,ČOKOLADA,PRAH,JAGODA,MLEKO',
'TORTILJA,SITI,SOMBRERO,ČILI,MEKSIKO',
'PRASE,JEŽ,PČELA,RUŽA,BODLJA',
'KAKTUS'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES ('TRUDNICA,GRČ,VARENJE,KISELINA,STOMAK',
'SAT,ĆELIJA,KINA,ŽIVI,ZID',
'KADA,OGLEDALO,TURSKA,TUŠ,KUPATILO',
'PEDALA,ZAUSTAVLJANJE,RUĆNA,ULJE,KOČNICA',
'PLOČICE'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'AMOROVA STRELA,KOMORA,LJUBAV,MIŠIĆ,SRCE',
'STAKLO,SLATKO,AJVAR,POKLOPAC,TEGLA',
'CVEĆE,STOKA,TRAVA,POLJANA,LIVADA',
'POŽAR,STABLA,ČETINARI,ROBIN HUD,ŠUMA',
'MED'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'RUSKA,KUPUS,VOĆE,CEZAR,SALATA',
'BRAVA,MATICA,EMISIJA,PRIVEZAK,KLJUČ',
'STRAST,OBRAZ,LJUBAV,VATRA,POLJUBAC',
'KUGLA,KREVET,BOLNICA,KAUČ,LEŽAJ',
'FRANCUSKI'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'DVORANA,DUBOK,RAZLIKA,GENERACIJA,JAZ',
'SOBA,JAPANKE,OBUĆA,LETO,PAPUČE',
'KAMEN,REČNO DNO,PESAK,BETON,ŠLJUNAK',
'ZAŠTITA,FRIKOM,SUNCE,PLATNO,SUNCOBRAN',
'PLAŽA'
);

INSERT INTO word_model (columnA, columnB, columnC, columnD, final_word) VALUES (
'GALAPAGOS,ZEC,MORE,SUPA,KORNJAČA',
'PERISKOP,ATOM,ŽIL VERN,KURSK,PODMORNICA',
'GUSENICA,T-84,BRDO,CEV,TENK',
'SREDNJI VEK,KOJA,HRABRI,OKRUGLI STO,VITEZ',
'OKLOP'
);

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'RODBINSKE VEZE',
'1:SNAJA, 2:JETRVA, 3:ZAOVA, 4:SVASTIKA, 5:ŠURNJAJA, 6:SVEKRVA, 7:TAŠTA, 8:STRINA',
'3:MUŽEVLJEVA SESTRA, 5:ŽENA ŽENINOG BRATA, 1:BRATOVA ŽENA, 8:ŽENA OČEVOG BRATA, 2:ŽENA MUŽEVLJEVOG BRATA, 4:ŽENINA SESTRA, 7:ŽENINA MAJKA, 6:MUŽEVLJEVA MAJKA'
);

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'SPOJITE GRADOVE SA SVOJIM NEKADAŠNJIM NAZIVIMA',
'1:BEOGRAD, 2:SREMSKA MITROVICA, 3:DŽAKARTA, 4:KNJAŽEVAC, 5:JAGODINA, 6:NJUJORK, 7: BRATISLAVA, 8:PODGORICA',
'5:SVETOZAREVO, 2:SIRMIJUM, 3:BATAVIJA, 8:TITOGRAD, 1:SINGIDUNUM, 4:GURGUSOVAC, 7:PRESBURG, 6:NOVI AMSTERDAM'
);

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'SPOJITE LIKOVE IZ CRTANIH FILMOVA SA ŽIVOTINJOM KOJU PREDSTAVLJAJU',
'1:SILVESTER, 2:MLATA, 3:BAJA, 4:DŽERI, 5:MANFRED, 6:MARTI, 7:GLORIJA, 8:MAJOR',
 '2:PAS, 5:MAMUT, 7:NILSKI KONJ, 3:PATAK, 6:ZEBRA, 1:MAČAK, 4:MIŠ, 8:PINGVIN'
 );

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'POVEŽITE SPORTSKE RIVALE',
'1:OLIMPIJAKOS, 2:ČELZI, 3:DINAMO, 4:SELTIK, 5:FEHERBAHČE, 6:LACIO, 7:BENFIKA, 8:AJAKS',
'4:RENDŽERS, 2:ARSENAL, 5:GALATASARAJ, 7:SPORTING, 3:HAJDUK, 6:ROMA, 8:FEJNORD, 1:PANATINIKOS'
);

INSERT INTO pairs_model (headline,column1, column2) VALUES(
'POVEŽITE GODINE I POBEDNIKE EUROSONGA:',
'1:2008., 2:2006., 3:2009., 4:2005., 5:2007., 6:2010., 7:2004., 8:2003.',
 '6:NEMAČKA-LENA, 2:FINSKA-LORDI, 5:SRBIJA-M.ŠERIFOVIĆ, 3:NORVEŠKA-A.RIBAK, 1:RUSIJA-DIMA BILAN, 8:TURSKA-S.ERENER, 4:GRČKA-H.PAPARIZOU, 7:UKRAJINA-RUSLANA'
 );
